version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8000 # Base URL for the backend API or http://backend:8000 when using Docker Compose
    depends_on:
      - backend